debug: true
spring:
  application:
    name: Tourism portal K. Okhrimenko
  thymeleaf:
    check-template-location: true
    prefix: classpath:/web/templates/pages/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    platform: h2
    initialization-mode: always
    url: jdbc:h2:mem:file-storage
    driverClassName: org.h2.Driver
    username: admin
    password:
  liquibase:
    enabled: true
    change-log: classpath:/db/liquibase-changeLog-init.xml
logging:
  file: /opt/application/logs/application.log
  level:
    root: ERROR
    org.springframework: ERROR
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"